/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedAuthRouteImport } from './routes/_unauthenticated/_auth'
import { Route as UnauthenticatedAuthSignupRouteImport } from './routes/_unauthenticated/_auth/signup'
import { Route as UnauthenticatedAuthLoginRouteImport } from './routes/_unauthenticated/_auth/login'
import { Route as UnauthenticatedAuthForgotPasswordRouteImport } from './routes/_unauthenticated/_auth/forgot-password'

const UnauthenticatedAuthRoute = UnauthenticatedAuthRouteImport.update({
  id: '/_unauthenticated/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedAuthSignupRoute =
  UnauthenticatedAuthSignupRouteImport.update({
    id: '/signup',
    path: '/signup',
    getParentRoute: () => UnauthenticatedAuthRoute,
  } as any)
const UnauthenticatedAuthLoginRoute =
  UnauthenticatedAuthLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => UnauthenticatedAuthRoute,
  } as any)
const UnauthenticatedAuthForgotPasswordRoute =
  UnauthenticatedAuthForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => UnauthenticatedAuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof UnauthenticatedAuthForgotPasswordRoute
  '/login': typeof UnauthenticatedAuthLoginRoute
  '/signup': typeof UnauthenticatedAuthSignupRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof UnauthenticatedAuthForgotPasswordRoute
  '/login': typeof UnauthenticatedAuthLoginRoute
  '/signup': typeof UnauthenticatedAuthSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_unauthenticated/_auth': typeof UnauthenticatedAuthRouteWithChildren
  '/_unauthenticated/_auth/forgot-password': typeof UnauthenticatedAuthForgotPasswordRoute
  '/_unauthenticated/_auth/login': typeof UnauthenticatedAuthLoginRoute
  '/_unauthenticated/_auth/signup': typeof UnauthenticatedAuthSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/forgot-password' | '/login' | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to: '/forgot-password' | '/login' | '/signup'
  id:
    | '__root__'
    | '/_unauthenticated/_auth'
    | '/_unauthenticated/_auth/forgot-password'
    | '/_unauthenticated/_auth/login'
    | '/_unauthenticated/_auth/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  UnauthenticatedAuthRoute: typeof UnauthenticatedAuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauthenticated/_auth': {
      id: '/_unauthenticated/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnauthenticatedAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/_auth/signup': {
      id: '/_unauthenticated/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof UnauthenticatedAuthSignupRouteImport
      parentRoute: typeof UnauthenticatedAuthRoute
    }
    '/_unauthenticated/_auth/login': {
      id: '/_unauthenticated/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UnauthenticatedAuthLoginRouteImport
      parentRoute: typeof UnauthenticatedAuthRoute
    }
    '/_unauthenticated/_auth/forgot-password': {
      id: '/_unauthenticated/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof UnauthenticatedAuthForgotPasswordRouteImport
      parentRoute: typeof UnauthenticatedAuthRoute
    }
  }
}

interface UnauthenticatedAuthRouteChildren {
  UnauthenticatedAuthForgotPasswordRoute: typeof UnauthenticatedAuthForgotPasswordRoute
  UnauthenticatedAuthLoginRoute: typeof UnauthenticatedAuthLoginRoute
  UnauthenticatedAuthSignupRoute: typeof UnauthenticatedAuthSignupRoute
}

const UnauthenticatedAuthRouteChildren: UnauthenticatedAuthRouteChildren = {
  UnauthenticatedAuthForgotPasswordRoute:
    UnauthenticatedAuthForgotPasswordRoute,
  UnauthenticatedAuthLoginRoute: UnauthenticatedAuthLoginRoute,
  UnauthenticatedAuthSignupRoute: UnauthenticatedAuthSignupRoute,
}

const UnauthenticatedAuthRouteWithChildren =
  UnauthenticatedAuthRoute._addFileChildren(UnauthenticatedAuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  UnauthenticatedAuthRoute: UnauthenticatedAuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
